export const STUDENT_CONSTANTS = {
    ADD_NEW_STUDENT: "ADD_NEW_STUDENT",
    GET_STUDENTS: "GET_STUDENTS",
    BEFORE_SEND: "BEFORE_SEND",
    GET_STUDENT: "GET_STUDENT",
    UPDATE_STUDENT: "UPDATE_STUDENT",
    CLEAR_ERRORS: "CLEAR_ERRORS",
    REQUEST_SUCCESSFUL: "REQUEST_SUCCESSFUL",
    IS_UPDATING: "IS_UPDATING",
    CLEAR_SUCCESS: "CLEAR_SUCCESS"
}
//0754678625